# -*- coding: utf-8 -*-
"""helloworld.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100QOaA_bVWrk3r6WvXroHbfxNVwCE5cc
"""

print("Hello world!")